package com.suraj.embeddingservice.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    DUPLICATE_CHUNK_IDS,
    CHUNK_FETCH_FAILED,
    CHUNK_CONTENT_EMPTY,
    CHECKSUM_VALIDATION_FAILED,
    EMBEDDING_GENERATION_FAILED,
    EMBEDDING_DIMENSION_MISMATCH,
    VECTOR_STORE_FAILED,
    EVENT_PUBLISH_FAILED,
    INTERNAL_ERROR
}
